#I am yaml commnt and present in generated yaml
{{- /* I am yaml commnet and not present in generated yaml*/}}
environment: {{ .Values.env }}
testdata: {{ lower .Values.mystring }}
newtestdata: {{ replace " " "-" .Values.mystring }}
labels:
  app: {{ .Release.Name }}
  chart: {{ .Chart.Name }}
